### ISSUE TITLE
Slim Framework 3

### ISSUE THREAD

**Issue by fearlex** [Botnary/wp-slim-framework#8]
Hey,

Love your plugin, any chance it can be upgraded to Slim 3 ?

Thanks

**Comment by Botnary** [comment]
Yes i will, i guess you could replace the `Slim` folder with the newer version and there is a chance it might work. I could use composer, but there is an issue if other plugins use composer too, and there are multiple `vendor/autoload.php`.

**Comment by fearlex** [comment]
Hey @Botnary 

Thanks for the response. I will definitively try it, and see if it works, i appreciate the work you did here, and was glad to know that such an integration was possible. 

I will be following this closely.

Thanks for your effort.
